tests/testthat/test-osm_bb.R
This test was left over from `osm_bb()`. I removed that function previously and now the commented-out test with it. `R CMD check` should pass now.
=> Drop traces of osm_bb() function

R/network.R, vignettes/corridor-segmentation.Rmd
This PR removes `filter_network()` from the list of exported functions, as it was only used in the `corridor-segmentation` vignette.
- Related Issue #89 
- Closes #89 
=> Remove filter_network from segmentation vignette

R/delineate.R
Before riverspace delineation, `river_centerline` is clipped to `aoi_buildings`. Riverspace delineation is almost three times faster in case of Bucharest (on my computer, reduced from 1.58 mins to 43 secs).
- Related Issue #105 
- Closes #105 
=> Clip river centerline before riverspace delineation

R/osmdata.R
Following @SarahAlidoost's #88, I removed the cropping of `river_surface`
- Related Issue #88 
- Closes #88 
=> Do not crop river_surface

R/osmdata.R, tests/testthat/test-osmdata.R
When trying to run riverspace delineation on `"Köln", "Rhein"`, I encountered invalid building polygons. This change in PR ensures that the polygons are made valid before being intersected with the aoi.
- Related Issue #
- Closes #
=> Fix invalid buildings retrieved from OSM

R/delineate.R, R/riverspace.R, man/delineate_riverspace.Rd, tests/testthat/test-riverspace.R
`delineate_riverspace` matches now the new signature of `get_isovist`
- Related Issue #123 
- Closes #123 
=> Match updated `visor::get_isovist()` in riverspace module

R/corridor.R, man/cap_corridor.Rd, man/delineate_corridor.Rd
This was already the default for `delineate`, but not for `delineate_corridor`
=> Change default capping to shortest path

R/osmdata.R, tests/testthat/test-osmdata.R
River surface can still be empty
=> Raise error if river geometry not found

R/osmdata.R, tests/testthat/test-osmdata.R
All values are retrieved from the OSM key `waterway`, not only `river`. Also, when generating the river centerline, `get_osm_river()` chooses the layer with the highest summed length between `$osm_line` and `$osm_multiline`.
- Related Issue #154 #155
- Closes #154 #155
=> Improved river centerline query

R/corridor.R
Problems might arise with rivers whose centerline is composed by multiple segments (e.g. due to the presence of islands).
See e.g. the case of Paris, for which I have encountered the issue when trying to lower the value `network_buffer` in order to improve the corridor delineation with meanders.   
The following script would return the problematic corridor:
```r
devtools::load_all()
city_name <- "Paris"
river_name <- "La Seine"
network_buffer <- 1500
dem_buffer <- 2500
force_download <- FALSE
bb <- CRiSp::get_osm_bb(city_name)
crs <- CRiSp::get_utm_zone(bb)
osm_data <- CRiSp::get_osmdata(
city_name, river_name, network_buffer = network_buffer,
buildings_buffer = NULL, city_boundary = FALSE, crs = crs,
force_download = force_download
)
aoi <- CRiSp::reproject(osm_data$aoi_network, crs) …
```
=> Issues with fragmented rivers

R/corridor.R, R/delineate.R, man/delineate.Rd, man/delineate_corridor.Rd
For some cases (e.g. Warsaw and Rome), the default value of network buffer is too small - we increase this from 2500m to 3000m
=> Increase default value of network buffer

R/osmdata.R, tests/testthat/test-osmdata.R
The following error is raised if we try to delineate a region without railways:
```
Error in UseMethod("select") : 
no applicable method for 'select' applied to an object of class "NULL"
Calls: retrieve_data ... get_network -> get_osm_railways -> <Anonymous> -> <Anonymous>
```
This fix allows `get_osm_railways` to return an empty `sf` object if no railways are found, so that the workflow can continue with the spatial network being based on streets only.
=> Return empty sf object if no railways are found

R/exampledata.R
Some of the checks are failing due to the `download.file` function timing out during vignette preparation or tests, this PR tries to solve the issue.
=> Increase timeout for example data retrieval

R/osmdata.R, tests/testthat/test-osmdata.R
* Adding partial matches for names and river - useful to retrieve some input data for the CRiSp dataset. Closes #67 , hope this is good enough even if we don't handle misspellings? 
* Search for city boundary in both OSM polygons and multipolygons (some cities, e.g. "Belfast", would be missed if only multipolygons are considered).
* A message that was printed out every time city boundaries are found is removed to reduce verbosity
=> Improvements for search for city boundaries

tests/testthat/test-osmdata.R
This fixes a test that was only failing locally (skipped on CI) after the `get_osm_city_boundary()` function was modified in #195.
- Related Issue #
- Closes #
=> Fix outdated city boundary test

R/osmdata.R, man/get_osm_railways.Rd
Small fixes in the osmdata module:
* Allow to specify arbitrary highway and railway values (currently there is a problem with the links in the street function)
* For the river centerline and surface, the osm_multi* geometries are in few cases not defined - rcrisp used to fail then.
=> Small fixes in OSM related functions

DESCRIPTION, NEWS.md, R/network.R, codemeta.json, cran-comments.md, man/clean_network.Rd, man/delineate_valley.Rd
The CRAN submission flagged the example in `clean_network()` as taking too long in “Examples with CPU (user + system) or elapsed time > 5s” or "> 10s". See logs below. With this PR, the example is only run in intercative mode. I also updated the version to 0.1.1.
```
Flavor: r-devel-windows-x86_64
Check: CRAN incoming feasibility, Result: NA
Maintainer: 'Claudiu Forgaci <EMAIL_REMOVED>'
New submission
Possibly misspelled words in DESCRIPTION:
Forgaci (16:60)
Flavor: r-devel-windows-x86_64
Check: examples, Result: NA
Examples with CPU (user + system) or elapsed time > 10s
user system elapsed
clean_network 13.84   1.31   15.42
Flavor: r-devel-windows-x86_64
Check: Overall checktime, Result: NOTE
Overall checktime 13 min > 10 min
Flavor: r-devel-linux-x86_64-debian-gcc
Check: CRAN incoming …
```
=> Fix clean network example performance cf

DESCRIPTION, NEWS.md, codemeta.json, cran-comments.md, tests/testthat/test-delineate.R, tests/testthat/test-valley.R
@fnattino, I mocked the two tests. Please have a look if this is what we need. Note that I had to decrease the precision in the `tolerance` parameter in the first test to make it pass.
=> Mock DEM retieval tests

R/srr-stats-standards.R
See [standards G2.0 and G2.1](https://stats-devguide.ropensci.org/standards.html#uni-variate-vector-input)
=> Update G2.0-2.1 compliance

DESCRIPTION
Should we then pin the minimum SF version?
=> Pin sf version

NEWS.md, R/corridor.R, tests/testthat/test-corridor.R
If the network does not cross the river at all, delineation will fail with an informative error.
- Related Issue #121
- Closes #121
=> Error when river has no crossings
